services:
  autoware:
    image: ghcr.io/autowarefoundation/autoware:universe-devel
    container_name: autoware
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///work/docker/cyclonedds.xml
    volumes:
      - ./:/work/docker:ro
      - ../scripts:/work/scripts:ro
      - ../reports:/work/reports
      - ~/autoware_map/nishishinjuku:/autoware_map/nishishinjuku:ro
      - ../extension/build:/work/extension:ro
    command: sleep infinity
